Importong Libraries

In [ ]:
# importing necessaries libraries
# LOGISTIC REGRESSION

# 1 numpy libraries used to make numpy arrays and use to  perform Mathematical operations

# 2 pandas is used to create dataframes and data frames are
#   structured table . Loading data in to data frames is  easier to analyze
#   the data and process the data.

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Loading csv file to Data Frame

In [ ]:
#Loading  data into data frame
df=pd.read_csv('CreditCard.csv')

In [ ]:
# df.head( ) is use to print the First Five rows

df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# df.tail() is use to print  the last fi ce rows of data set

df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [ ]:
# df.info() is use to print all information about data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [ ]:
# printing the total numbers  of rows and total  number of columns

df.shape

(284807, 31)

In [ ]:
# checking the Number of Missing values
# print(df.isnull().sum()) re turns the number of missing values

print(df.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# Dropping Missing Values
df=df.dropna()

In [ ]:
#after Dropping Missing values  checking again

print(df.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# use to  find the Duplicates from the data sets

df[df.duplicated()]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
33,26.0,-0.529912,0.873892,1.347247,0.145457,0.414209,0.100223,0.711206,0.176066,-0.286717,...,0.046949,0.208105,-0.185548,0.001031,0.098816,-0.552904,-0.073288,0.023307,6.14,0
35,26.0,-0.535388,0.865268,1.351076,0.147575,0.433680,0.086983,0.693039,0.179742,-0.285642,...,0.049526,0.206537,-0.187108,0.000753,0.098117,-0.553471,-0.078306,0.025427,1.77,0
113,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
114,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
115,74.0,1.038370,0.127486,0.184456,1.109950,0.441699,0.945283,-0.036715,0.350995,0.118950,...,0.102520,0.605089,0.023092,-0.626463,0.479120,-0.166937,0.081247,0.001192,1.18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282987,171288.0,1.912550,-0.455240,-1.750654,0.454324,2.089130,4.160019,-0.881302,1.081750,1.022928,...,-0.524067,-1.337510,0.473943,0.616683,-0.283548,-1.084843,0.073133,-0.036020,11.99,0
283483,171627.0,-1.464380,1.368119,0.815992,-0.601282,-0.689115,-0.487154,-0.303778,0.884953,0.054065,...,0.287217,0.947825,-0.218773,0.082926,0.044127,0.639270,0.213565,0.119251,6.82,0
283485,171627.0,-1.457978,1.378203,0.811515,-0.603760,-0.711883,-0.471672,-0.282535,0.880654,0.052808,...,0.284205,0.949659,-0.216949,0.083250,0.044944,0.639933,0.219432,0.116772,11.93,0
284191,172233.0,-2.667936,3.160505,-3.355984,1.007845,-0.377397,-0.109730,-0.667233,2.309700,-1.639306,...,0.391483,0.266536,-0.079853,-0.096395,0.086719,-0.451128,-1.183743,-0.222200,55.66,0
284193,172233.0,-2.691642,3.123168,-3.339407,1.017018,-0.293095,-0.167054,-0.745886,2.325616,-1.634651,...,0.402639,0.259746,-0.086606,-0.097597,0.083693,-0.453584,-1.205466,-0.213020,36.74,0

In [ ]:
# Printing the Number of Duplicate rows

duplicate_rows_df=df[df.duplicated()]
print("Number of Duplicate rows : ", duplicate_rows_df)

Number of Duplicate rows :              Time        V1        V2        V3        V4        V5        V6  \
33          26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223
35          26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983
113         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
114         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
115         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283
...          ...       ...       ...       ...       ...       ...       ...
282987  171288.0  1.912550 -0.455240 -1.750654  0.454324  2.089130  4.160019
283483  171627.0 -1.464380  1.368119  0.815992 -0.601282 -0.689115 -0.487154
283485  171627.0 -1.457978  1.378203  0.811515 -0.603760 -0.711883 -0.471672
284191  172233.0 -2.667936  3.160505 -3.355984  1.007845 -0.377397 -0.109730
284193  172233.0 -2.691642  3.123168 -3.339407  1.017018 -0.293095 -0.167054

              V7        V8        V9  ...       V21       V22       V23  \
33      0.711206  0.176066 -0.286717  ...  0.046949  0.208105 -0.185548
35      0.693039  0.179742 -0.285642  ...  0.049526  0.206537 -0.187108
113    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
114    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
115    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092
...          ...       ...       ...  ...       ...       ...       ...
282987 -0.881302  1.081750  1.022928  ... -0.524067 -1.337510  0.473943
283483 -0.303778  0.884953  0.054065  ...  0.287217  0.947825 -0.218773
283485 -0.282535  0.880654  0.052808  ...  0.284205  0.949659 -0.216949
284191 -0.667233  2.309700 -1.639306  ...  0.391483  0.266536 -0.079853
284193 -0.745886  2.325616 -1.634651  ...  0.402639  0.259746 -0.086606

             V24       V25       V26       V27       V28  Amount  Class
33      0.001031  0.098816 -0.552904 -0.073288  0.023307    6.14      0
35      0.000753  0.098117 -0.553471 -0.078306  0.025427    1.77      0
113    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
114    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
115    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0
...          ...       ...       ...       ...       ...     ...    ...
282987  0.616683 -0.283548 -1.084843  0.073133 -0.036020   11.99      0
283483  0.082926  0.044127  0.639270  0.213565  0.119251    6.82      0
283485  0.083250  0.044944  0.639933  0.219432  0.116772   11.93      0
284191 -0.096395  0.086719 -0.451128 -1.183743 -0.222200   55.66      0
284193 -0.097597  0.083693 -0.453584 -1.205466 -0.213020   36.74      0

[1081 rows x 31 columns]

In [ ]:
# Dropping  the Duplicates

df=df.drop_duplicates()
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# changing the Data Type  of  Class

df['Class']=df['Class'].astype(int)

In [ ]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
#distribution of legic transactions and frauduent transactions

df['Class'].value_counts()

0    283253
1       473
Name: Class, dtype: int64

Here 0 represent the Normal Representation  and 1 represent  the Fraudulent transaction.
the dataset  are highly unbalance

In [ ]:
#  fot data analysis we seperating the  data
legit=df[df.Class ==0]
fraud=df[df.Class ==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(283253, 31)
(473, 31)

In [ ]:
legit.Amount.describe()

count    283253.000000
mean         88.413575
std         250.379023
min           0.000000
25%           5.670000
50%          22.000000
75%          77.460000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     473.000000
mean      123.871860
std       260.211041
min         0.000000
25%         1.000000
50%         9.820000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions

df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94835.058093,0.013439,-0.009829,0.012853,-0.010440,0.006769,0.001251,0.010447,-0.002448,0.002613,...,-0.000489,-0.00115,-0.000160,0.000360,0.000393,-0.000301,0.000065,0.001409,0.000418,88.413575
1,80450.513742,-4.498280,3.405965,-6.729599,4.472591,-2.957197,-1.432518,-5.175912,0.953255,-2.522124,...,0.405043,0.46655,0.086639,-0.096464,-0.106643,0.040615,0.050456,0.213774,0.078270,123.871860

Under Smapling

Building sample data set from  original  dataset  Containing similar to normal transactions  and fraudulent transactions

In [ ]:
legit_sample=legit.sample(n=73)

Concatinating Two Data  frames

In [ ]:
new_df=pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
65089,51425.0,-0.924064,0.503808,1.727170,2.329890,-0.986781,0.624637,1.397555,-0.526707,-0.626484,...,-0.419233,-0.537032,0.162231,0.455541,-0.890864,0.774520,-0.222923,-0.079113,257.54,0
134223,80705.0,-0.817190,-1.172546,2.258666,-1.576158,-0.761763,-0.153492,-0.411182,0.094877,-0.691863,...,0.045605,0.331966,0.291491,-0.003971,-0.807435,0.868204,-0.109285,-0.056311,125.90,0
161746,114479.0,2.000111,-0.462827,-2.642309,-0.666760,2.396993,3.343997,-0.409997,0.775232,0.438966,...,-0.237727,-0.690928,0.302313,0.714787,-0.169313,0.294706,-0.059398,-0.065703,27.97,0
134252,80716.0,1.254907,-0.894202,1.184673,-0.325240,-1.725984,-0.368837,-1.045194,0.019483,-0.048624,...,-0.457133,-0.732628,0.111361,0.418213,-0.004671,0.956125,-0.011803,0.028190,43.50,0
165766,117648.0,-1.269213,1.753733,-0.276113,-1.038781,0.593861,-1.155562,1.396525,-0.776788,1.521205,...,0.064631,0.982894,-0.320672,-0.081977,0.130449,-0.304232,-0.616519,-0.612095,0.89,0

In [ ]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [ ]:
# Counting the Values of normal Transactions and Fraudlent Transactions from new data frame

new_df['Class'].value_counts()

1    473
0     73
Name: Class, dtype: int64

In [ ]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,99875.438356,0.056063,-0.018062,0.102780,0.089279,0.013075,0.038836,0.019447,-0.201432,0.136681,...,0.033230,0.005749,0.091227,0.015924,-0.006928,-0.100984,-0.012718,-0.072790,-0.039907,93.003699
1,80450.513742,-4.498280,3.405965,-6.729599,4.472591,-2.957197,-1.432518,-5.175912,0.953255,-2.522124,...,0.405043,0.466550,0.086639,-0.096464,-0.106643,0.040615,0.050456,0.213774,0.078270,123.871860

In [ ]:
x=new_df.drop(columns='Class',axis=1)
y=new_df['Class']

In [ ]:
x

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
65089,51425.0,-0.924064,0.503808,1.727170,2.329890,-0.986781,0.624637,1.397555,-0.526707,-0.626484,...,-0.129521,-0.419233,-0.537032,0.162231,0.455541,-0.890864,0.774520,-0.222923,-0.079113,257.54
134223,80705.0,-0.817190,-1.172546,2.258666,-1.576158,-0.761763,-0.153492,-0.411182,0.094877,-0.691863,...,-0.029547,0.045605,0.331966,0.291491,-0.003971,-0.807435,0.868204,-0.109285,-0.056311,125.90
161746,114479.0,2.000111,-0.462827,-2.642309,-0.666760,2.396993,3.343997,-0.409997,0.775232,0.438966,...,-0.106726,-0.237727,-0.690928,0.302313,0.714787,-0.169313,0.294706,-0.059398,-0.065703,27.97
134252,80716.0,1.254907,-0.894202,1.184673,-0.325240,-1.725984,-0.368837,-1.045194,0.019483,-0.048624,...,-0.398014,-0.457133,-0.732628,0.111361,0.418213,-0.004671,0.956125,-0.011803,0.028190,43.50
165766,117648.0,-1.269213,1.753733,-0.276113,-1.038781,0.593861,-1.155562,1.396525,-0.776788,1.521205,...,0.557605,0.064631,0.982894,-0.320672,-0.081977,0.130449,-0.304232,-0.616519,-0.612095,0.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [ ]:
y

65089     0
134223    0
161746    0
134252    0
165766    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 546, dtype: int64

Spliting data into training data and testing data

In [ ]:
# Here we Creating the 4 arrays x_train,x_test,y_train,y_test
# Here x represents the features and y represents the Labels
# all features are stored in x_train and x_test and Labels are stored in y_train and y_test

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2,stratify=y)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(546, 30) (436, 30) (110, 30)

Model Training

Logistic Regression

In [ ]:
model=LogisticRegression()

In [ ]:
#Training the logistic Regression model with Training Data

model.fit(x_train,y_train)

LogisticRegression()

 model  Evaluation.

 Accuracy Score

In [ ]:
# Accuracy of Training data

x_train_prediction=model.predict(x_train)
accuracy=accuracy_score(x_train_prediction,y_train)

In [ ]:
print('The Accuracy is : ' ,accuracy)

The Accuracy is :  0.944954128440367

In [ ]:
# accuracy of Test data

x_test_prediction=model.predict(x_test)
test_accuracy=accuracy_score(x_test_prediction,y_test)

In [ ]:
print('Accuracy of Test Data : ',test_accuracy)

Accuracy of Test Data :  0.9090909090909091